type Deposit {
  id: String!
  sender: String!
  value: String!
  tx_hash: String!
  created_at: Int!
  created_at_block: Int!
}

type Withdraw {
  id: String!
  sender: String!
  value: String!
  tx_hash: String!
  created_at: Int!
  created_at_block: Int!
}

type ClaimRewards {
  id: String!
  sender: String!
  value: String!
  tx_hash: String!
  created_at: Int!
  created_at_block: Int!
}

type Rebalanced {
  id: String!
  value: String!
  tx_hash: String!
  created_at: Int!
  created_at_block: Int!
}
